NAME: 'Breakout Trend Following'
MODULE: 'breakout'
CLASS: 'Breakout'
INTERVAL: '3s'
PARAMETERS:
  sl_distance_pc: 5
  tp_distance_pc: 5
  size_multiplier: 2
  trend_interval: '1m'
  trend_ema_period: 500
  tp_after_loss: 5
  entry_value: 1
  loops: 1
WATCHLIST: ['RSR/USDT:USDT']
INCLUDE: ["INTERVAL"] # used when displaying params in CLI, exclude others
BACKTEST_READY: False
