NAME: 'Range Bound Grid Trading'
MODULE: 'range'
CLASS: 'Range'
INTERVAL: '10s'
PARAMETERS:
  lower_price: 50
  upper_price: 60
  no_levels: 40
  max_position: 20
WATCHLIST: ['AVAX/USDT:USDT']
INCLUDE: ["INTERVAL"] # used when displaying params in CLI, exclude others
BACKTEST_READY: False
