KEYS_FILENAME = "keys.yaml"
STRATEGY_DIRECTORY = "strategies"
CONFIG_DIRECTORY = "config"
USER_CONFIG_DIRECTORY = "user_configurations"
INIT_FILE = ".initialised"
STRFTIME = "%Y-%m-%d"
DEFAULT_HOME_DIRECTORY = ".cryptobots"
